index:
  credentials: [edit_disciplinary_sanction_type]

new:
  credentials: [edit_disciplinary_sanction_type]

create:
  credentials: [edit_disciplinary_sanction_type]

edit:
  credentials: [edit_disciplinary_sanction_type]

update:
  credentials: [edit_disciplinary_sanction_type]

delete:
  credentials: [edit_disciplinary_sanction_type]

