index:
  credentials: [edit_absence_type]

new:
  credentials: [edit_absence_type]

create:
  credentials: [edit_absence_type]

edit:
  credentials: [edit_absence_type]

update:
  credentials: [edit_absence_type]

delete:
  credentials: [edit_absence_type]

