index:
  credentials:   [show_career_school_year]

create_career_school_year:
  credentials:  [edit_career_school_year]

configuration:
  credentials:  [edit_career_school_year]

updateConfiguration:
  credentials:  [edit_career_school_year]

career_subject_school_year:
  credentials:  [show_career_school_year]

optionals:
  credentials:  [show_career_school_year]

delete:
  credentials:  [edit_career_school_year]
